### ISSUE TITLE
Not working with custom palette

### ISSUE THREAD

**Issue by TaylanTatli** [nukeop/cadmium#1]
It's working with the palettes in your repo but it's not working with mines.

```
thread 'main' panicked at 'byte index 1 is out of bounds of ``', library/core/src/str/mod.rs:107:9
stack backtrace:
   0:     0x55d43cc2a08d - std::backtrace_rs::backtrace::libunwind::trace::h2f06c59e048fd6ef
                               at /rustc/1.62.1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d43cc2a08d - std::backtrace_rs::backtrace::trace_unsynchronized::h312b5329d9b90799
                               at /rustc/1.62.1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d43cc2a08d - std::sys_common::backtrace::_print_fmt::hc5df6e0ae92eab3d
                               at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55d43cc2a08d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h507aa611980ef3ae
                               at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55d43cc4c0ac - core::fmt::write::h84a77b5d03a4d9fd
                               at /rustc/1.62.1/library/core/src/fmt/mod.rs:1196:17
   5:     0x55d43cc271e1 - std::io::Write::write_fmt::hee6101c2ca4f56a1
                               at /rustc/1.62.1/library/std/src/io/mod.rs:1654:15
   6:     0x55d43cc2b885 - std::sys_common::backtrace::_print::h9691b5acf5a0c0cc
                               at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55d43cc2b885 - std::sys_common::backtrace::print::h0a5971ff57f37f1d
                               at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55d43cc2b885 - std::panicking::default_hook::{{closure}}::he4caf87b461ee958
                               at /rustc/1.62.1/library/std/src/panicking.rs:295:22
   9:     0x55d43cc2b4f9 - std::panicking::default_hook::had807c37bcc92c12
                               at /rustc/1.62.1/library/std/src/panicking.rs:314:9
  10:     0x55d43cc2be58 - std::panicking::rust_panic_with_hook::hfcce4455d4fbb45f
                               at /rustc/1.62.1/library/std/src/panicking.rs:698:17
  11:     0x55d43cc2bd07 - std::panicking::begin_panic_handler::{{closure}}::h930a070c36da4819
                               at /rustc/1.62.1/library/std/src/panicking.rs:588:13
  12:     0x55d43cc2a544 - std::sys_common::backtrace::__rust_end_short_backtrace::h4dc186497cf8346b
                               at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55d43cc2ba39 - rust_begin_unwind
                               at /rustc/1.62.1/library/std/src/panicking.rs:584:5
  14:     0x55d43c351f83 - core::panicking::panic_fmt::h7acba03dfd87b5f5
                               at /rustc/1.62.1/library/core/src/panicking.rs:142:14
  15:     0x55d43cc4f3ab - core::str::slice_error_fail_rt::h5baf22de71359956
  16:     0x55d43cc44b47 - core::ops::function::FnOnce::call_once::he90d79919fb7c963
                               at /rustc/1.62.1/library/core/src/ops/function.rs:248:5
  17:     0x55d43cc496d8 - core::intrinsics::const_eval_select::hc7c90f6a0e434b67
                               at /rustc/1.62.1/library/core/src/intrinsics.rs:2372:5
  18:     0x55d43c352242 - core::str::slice_error_fail::h006fa0b958614c1a
                               at /rustc/1.62.1/library/core/src/str/mod.rs:86:9
  19:     0x55d43c4ca0f7 - core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index::h98330149a5af2920
                               at /rustc/1.62.1/library/core/src/str/traits.rs:218:21
  20:     0x55d43c4ccb07 - core::str::traits::<impl core::ops::index::Index<I> for str>::index::h48452ebfcc140664
                               at /rustc/1.62.1/library/core/src/str/traits.rs:65:9
  21:     0x55d43c35844c - cadmium::palette::Palette::from_file::{{closure}}::hc7c0e9391d9fc257
                               at /home/taylantatli/cadmium/src/palette.rs:33:41
  22:     0x55d43c3549af - core::iter::adapters::map::map_fold::{{closure}}::h1d399f63acaecc2f
                               at /rustc/1.62.1/library/core/src/iter/adapters/map.rs:84:28
  23:     0x55d43c354b3a - core::iter::traits::iterator::Iterator::fold::h8e989d8fca7d8c10
                               at /rustc/1.62.1/library/core/src/iter/traits/iterator.rs:2366:21
  24:     0x55d43c35477d - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h31246d98682e49f9
                               at /rustc/1.62.1/library/core/src/iter/adapters/map.rs:124:9
  25:     0x55d43c3548ce - core::iter::traits::iterator::Iterator::for_each::h9c21c968661bc2f1
                               at /rustc/1.62.1/library/core/src/iter/traits/iterator.rs:783:9
  26:     0x55d43c35819f - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::hd1eae53002d86f5a
                               at /rustc/1.62.1/library/alloc/src/vec/spec_extend.rs:40:17
  27:     0x55d43c357766 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::hcabcf69d362a94af
                               at /rustc/1.62.1/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  28:     0x55d43c35821b - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hfca773a74f248912
                               at /rustc/1.62.1/library/alloc/src/vec/spec_from_iter.rs:33:9
  29:     0x55d43c357f07 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h90bcf08d290df728
                               at /rustc/1.62.1/library/alloc/src/vec/mod.rs:2612:9
  30:     0x55d43c35483b - core::iter::traits::iterator::Iterator::collect::hcede0312b405abef
                               at /rustc/1.62.1/library/core/src/iter/traits/iterator.rs:1788:9
  31:     0x55d43c3535a5 - cadmium::palette::Palette::from_file::h859dbe87cf5b27d4
                               at /home/taylantatli/cadmium/src/palette.rs:29:26
  32:     0x55d43c352dec - cadmium::main::h15aad781bd8450e2
                               at /home/taylantatli/cadmium/src/main.rs:32:19
  33:     0x55d43c352fcb - core::ops::function::FnOnce::call_once::h714eb12e08c979f7
                               at /rustc/1.62.1/library/core/src/ops/function.rs:248:5
  34:     0x55d43c35250e - std::sys_common::backtrace::__rust_begin_short_backtrace::h8a6848b51dac90e4
                               at /rustc/1.62.1/library/std/src/sys_common/backtrace.rs:122:18
  35:     0x55d43c3533b1 - std::rt::lang_start::{{closure}}::h83e7ac2b07cca92a
                               at /rustc/1.62.1/library/std/src/rt.rs:145:18
  36:     0x55d43cc21f7e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h641d9fa5e70e9fbd
                               at /rustc/1.62.1/library/core/src/ops/function.rs:280:13
  37:     0x55d43cc21f7e - std::panicking::try::do_call::h1406d4a9807cb706
                               at /rustc/1.62.1/library/std/src/panicking.rs:492:40
  38:     0x55d43cc21f7e - std::panicking::try::h90869cc93eaa8e62
                               at /rustc/1.62.1/library/std/src/panicking.rs:456:19
  39:     0x55d43cc21f7e - std::panic::catch_unwind::h952a3e5ebc112269
                               at /rustc/1.62.1/library/std/src/panic.rs:137:14
  40:     0x55d43cc21f7e - std::rt::lang_start_internal::{{closure}}::h47917acef155c91d
                               at /rustc/1.62.1/library/std/src/rt.rs:128:48
  41:     0x55d43cc21f7e - std::panicking::try::do_call::hb70d9eb9d9f620d2
                               at /rustc/1.62.1/library/std/src/panicking.rs:492:40
  42:     0x55d43cc21f7e - std::panicking::try::h17507e57b1cb3a18
                               at /rustc/1.62.1/library/std/src/panicking.rs:456:19
  43:     0x55d43cc21f7e - std::panic::catch_unwind::h238fa938792f254f
                               at /rustc/1.62.1/library/std/src/panic.rs:137:14
  44:     0x55d43cc21f7e - std::rt::lang_start_internal::h60cd4444337b7dae
                               at /rustc/1.62.1/library/std/src/rt.rs:128:20
  45:     0x55d43c353380 - std::rt::lang_start::h14dd18ce4297c3a4
                               at /rustc/1.62.1/library/std/src/rt.rs:144:17
  46:     0x55d43c352f4c - main
  47:     0x7faf13a29290 - <unknown>
  48:     0x7faf13a2934a - __libc_start_main
  49:     0x55d43c352275 - _start
                               at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
  50:                0x0 - <unknown>
```

Here is the palette I'm trying to use:

```
#1b2031
#414868
#f7768e
#41b59b
#e0af68
#7ba2f3
#bb9af7
#2ccee9
#c0caf5
#414868
#f7768e
#41b59c
#e0af68
#7ba2f3
#bb9af7
#2ac4df
```

**Comment by nukeop** [comment]
Fixed, now it will ignore empty lines

**Comment by TaylanTatli** [comment]
Thank you.
